name: Build and deploy Python app to Azure Web App - prioritycare-sait

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip . --exclude "*.git*" --exclude "__pycache__/*" --exclude "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A740EFAE70B849FAB0A9C88DC9EE0F3C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95A031558C6B4139AF7BBB7FD1191A96 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C23318E288A4C6CB5B61F845B360975 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prioritycare-sait'
          slot-name: 'Production'
          package: release.zip
